In [1]:
import tensorflow as tf

In [2]:
tf.InteractiveSession()

In [11]:
#  2 by 2 tensor filled with zeros
tf.zeros(2)

<tf.Tensor 'zeros_2:0' shape=(2,) dtype=float32>

In [14]:
# t.zeros returns ref to 2 by 2 tensor, eval returns values in numpy array
tf.zeros(2).eval()

array([ 0.,  0.], dtype=float32)

In [12]:
# 2 by 2 tensor filled with ones
tf.ones(2)

<tf.Tensor 'ones_3:0' shape=(2,) dtype=float32>

In [13]:
# Fill 2 by 5 tensor with .5
tf.fill((2,5),.5).eval()

array([[ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5]], dtype=float32)

In [16]:
# this will remain constant in program execution
a = tf.constant(2)
a.eval()

2

In [21]:
# random initialization
tf.random_normal([2,2], mean=1, stddev=.1).eval()

array([[ 1.04067445,  1.13036394,  0.83581066, ...,  1.00158787,
         1.04807329,  1.11631727],
       [ 1.1499933 ,  1.09391892,  1.05183697, ...,  0.90872943,
         1.05934024,  0.87055463],
       [ 1.01508963,  0.97466826,  1.03311729, ...,  1.00153935,
         0.85718715,  1.16791773],
       ..., 
       [ 0.96861416,  1.0544672 ,  0.92774355, ...,  0.98630106,
         0.96103626,  1.01791537],
       [ 1.0284704 ,  0.9701553 ,  0.92653161, ...,  0.84988004,
         1.07932711,  0.97326726],
       [ 1.06809735,  0.98144335,  1.10097921, ...,  1.07472765,
         1.04167807,  1.01967156]], dtype=float32)

In [22]:
# machine learning systems often use 10s of millions of draws from the normal distribution - common to truncate so that values more than 2`std from mean are dropped - prevents numerical instability
tf.truncated_normal([50,50], mean=1, stddev=.1).eval()

array([[ 1.07196844,  1.04652119,  1.09952724, ...,  0.85826182,
         0.96650171,  1.19188964],
       [ 0.83888865,  1.00935924,  0.987059  , ...,  1.08838677,
         0.87944961,  0.86754155],
       [ 0.95023119,  0.90048409,  0.98104817, ...,  1.0950557 ,
         1.02621651,  1.17175376],
       ..., 
       [ 0.80624425,  1.11394262,  0.89505762, ...,  1.08744872,
         1.01545227,  0.8990075 ],
       [ 1.05222201,  0.99002153,  0.98323321, ...,  1.11792016,
         0.86173791,  1.05400038],
       [ 0.97134161,  1.18595338,  0.86576891, ...,  0.97257715,
         1.06017005,  0.91200233]], dtype=float32)

In [25]:
# other distributions
tf.random_uniform([2,3]).eval()

array([[ 0.24846637,  0.93894482,  0.23314178],
       [ 0.43553889,  0.84314048,  0.11421597]], dtype=float32)

In [30]:
# basic operations
c = tf.ones((2,2))
d = tf.ones((2,2))
print((c+d).eval())

# elementwise, not matrix multiplication
e = tf.fill((2,2),.5)
print((c*e).eval())

print ((2*e).eval())

[[ 2.  2.]
 [ 2.  2.]]
[[ 0.5  0.5]
 [ 0.5  0.5]]
[[ 1.  1.]
 [ 1.  1.]]


In [32]:
# matrix operations
print(tf.eye(2,2).eval())


# diagonal matrix
r = tf.range(1,5,1)
print(r.eval())
d=tf.diag(r)
print(d.eval())

[[ 1.  0.]
 [ 0.  1.]]
[1 2 3 4]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [35]:
# transpose
a = tf.ones((2,3))
print(a.eval())
at = tf.matrix_transpose(a)
print(at.eval())

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [36]:
# matrix multiplication
a = tf.ones((2,3))
print(a.eval())
b=tf.ones((3,4))
print(b.eval())
c = tf.matmul(a,b)
print(c.eval())

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]


In [37]:
# type conversions
print(tf.to_float(c))
print(tf.to_double(c))
print(tf.to_int32(c))
print(tf.to_int64(c))

Tensor("MatMul:0", shape=(2, 4), dtype=float32)
Tensor("ToDouble:0", shape=(2, 4), dtype=float64)
Tensor("ToInt32:0", shape=(2, 4), dtype=int32)
Tensor("ToInt64:0", shape=(2, 4), dtype=int64)


In [40]:
# shape manipulation - can move between rank-1, rank-2, rank-3 tensors easily
a = tf.ones(8)
print(a.eval())
print(a.get_shape())
b = tf.reshape(a, (4,2))
print(b.eval())
print(b.get_shape())
c=tf.reshape(a, (2,2,2))
print(c.eval())
print(c.get_shape())

# tf.squeeze removes all dimensions of size 1
# tf.expand_dims adds an extra dimension

[ 1.  1.  1.  1.  1.  1.  1.  1.]
(8,)
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
(4, 2)
[[[ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]]]
(2, 2, 2)
